services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    image: local/pokemon-app-api
    volumes:
      - ./server:/api
    ports:
      - 5001:5001
      - 5678:5678
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    image: local/pokemon-app-client
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"